from django.urls import include, path
from . import views

app_name = 'Product_details'

urlpatterns = [
  
    path('addpoints/', views.add_points),
    path('updatepoints/<int:product_id>/', views.update_points),
    path('deletepoints/<int:product_id>/', views.delete_points),
    path('addprice/', views.add_price),
    path('updateprice/<int:product_id>/', views.update_price),
    path('deleteprice/<int:product_id>/', views.delete_price),
    path('addspec/', views.add_specification),
    path('add_specification/<int:product_id>/', views.add_spec),
    path('add_specification1/<int:product_id>/', views.add_spec2),
    #path('add_specification/<int:product_id>/', views.add_spec),
    path('edit_specification/<int:specification_id>/', views.edit_spec),
    path('delete_specification/<int:specification_id>/', views.delete_spec),
    path('updatespec/<int:product_id>/', views.update_specification),
    path('deletespec/<int:product_id>/', views.delete_specification),
    path('showspec/<int:product_id>/', views.show_specification,name='showspec'),
    path('showsellerspec/<int:product_id>/', views.show_seller_specification),
    path('show/<int:product_id>/', views.show),
    path('transfer/<int:user_id>/',views.transfer),
    path('detail/<int:product_id>/', views.product_detail),
  
    path('create_cupon/', views.insert_cupon),
    path('all_cupon/', views.get_all_cupons),
    path('update_cupon/<int:cupon_id>/', views.update_specific_cupons),
    path('delete_cupon/<int:cupon_id>/', views.delete_specific_cupons),

    path('all_discount/', views.get_all_discount_value), 
    path('specific_value/<int:product_id>/', views.get_update_specific_value),
    path('insert_specific/', views.insert_specific_discount_value),
    path('discount_delete/<int:product_id>/', views.delete_discount_value),
    # path('details_order/<int:order_id>/', views.get_product_lists),
    # path('confirm_order/', views.confirm_products),
    # path('inventory_lists/<int:order_details_id>/', views.get_inventory_lists),
    # path('subtract_quantity/<int:order_details_id>/', views.subtract_quantity),
    path('inventory_lists/<int:order_details_id>/',views.inventory_lists),
    path('admin_approval/<int:order_id>/', views.admin_approval),
    path('admin_cancellation/<int:order_id>/', views.admin_cancellation),
    path('available_colors/<int:product_id>/', views.color_size),
    path('available_sizes/<int:product_id>/', views.available_sizes),
    path('create_warehouse/', views.create_warehouse),
    path('create_shop/', views.create_shop),
    path('update_warehouse/<int:warehouse_id>/', views.update_warehouse),
    path('update_shop/<int:shop_id>/', views.update_shop),
    path('warehouses/', views.show_all_warehouses),
    path('shops/', views.show_all_shops),
    path('delete_warehouse/<int:warehouse_id>/', views.delete_warehouse),
    path('delete_shop/<int:shop_id>/', views.delete_shop),
    path('warehouse_products/<int:warehouse_id>/', views.warehouse_products),
    path('subtract_items/<int:order_details_id>/', views.subtract_items),
    path('subtract_spec_quantity/<int:specification_id>/', views.subtract_spec_quantity),
    path('item_cancellation/<int:order_details_id>/', views.item_cancellation),


    path('insert_quantity/', views.insert_product_quantity),
    path('seller_insert_quantity/', views.seller_insert_product_quantity),
    path('shop_products/<int:shop_id>/', views.shop_products),
    path('quantity_info/<int:specification_id>/', views.get_all_quantity_list),
    # path('purchase_quantity_info/<int:specification_id>/', views.get_all_quantity_list_and_price),
    # path('subtract_items/', views.subtract_items),
    path('create_brand/', views.create_all_brand),
    path('get_brands/', views.get_all_brand),
    path('delete_brand/<int:brand_id>/', views.delete_specific_brand),
    path('update_brand/<int:brand_id>/', views.update_specific_brand),
    path('get_colors/<int:product_id>/', views.get_colors),
    path('get_sizes/<int:product_id>/', views.get_sizes),
    path('get_spec_info/<int:product_id>/', views.get_spec_info),
    path('warehouse_report/', views.warehouse_report),
    path('shop_report/', views.shop_report),
    path('purchase_reports/', views.purchase_reports),
    path('merchantproducts/<int:seller_id>/', views.merchant_products),
    path('get_subtracted_value/<int:order_id>/<int:specification_id>', views.get_subtracted_value),


    path('add_merchant_spec/<int:product_id>/', views.merchant_spec),
    path('edit_merchant_spec/<int:specification_id>/', views.merchant_spec_edit),
    path('individual_seller_spec/<int:specification_id>/', views.individual_seller_spec),
    path('cancel_invoice/<int:invoice_id>/', views.cancel_invoice),
    path('deliveryinfo/<int:specification_id>/', views.get_delivery_info),
    path('verify_pos/', views.verify_pos),
    path('warehouse_shop_info/', views.warehouse_shop_info),
    path('create_terminal/', views.create_terminal),
    path('terminal_list/', views.terminal_list),
    path('create_pos_user/<int:terminal_id>/', views.create_pos_user),
    path('make_terminal_active_inactive/<int:terminal_id>/', views.make_terminal_active_inactive),
    path('make_user_active_inactive/<int:user_id>/<int:terminal_id>/', views.make_user_active_inactive),
    # path('create_pos_user/<int:terminal_id>/', views.create_pos_user),
    path('insert_specification_price/<int:specification_id>/', views.insert_specification_price),
    path('mothersite_approval_response/<int:specification_id>/', views.mothersite_approval_response),
    path('mothersite_cancelled_response/<int:specification_id>/', views.mothersite_cancelled_response),
    path('all_shared_motherproducts/', views.all_shared_motherproducts),
    path('all_own_shared_products/', views.all_shared_products),
    path('approved_own_shared_products/', views.approved_shared_products),
    path('pending_own_shared_products/', views.pending_shared_products),
    path('cancelled_own_shared_products/', views.cancelled_shared_products),
    path('all_mothersite_products/', views.all_mothersite_products),
    path('individual_specs/<int:specification_id>/', views.individual_specs),
    path('bring_product/<int:mother_specification_id>/', views.bring_product),
    path('getunshared_spec/', views.unsharedSpecification),
    path('own_quantity_check/<int:specification_id>/', views.own_quantity_check),
    path('not_own_quantity_check/<int:specification_id>/', views.not_own_quantity_check),
    path('update_max_min_values/<int:specification_id>/', views.update_max_min_values),
    path('check_price/<int:specification_id>/', views.check_price),
    path('approve_purchase_order/<int:order_id>/', views.approve_purchase_order),
    path('insert_purchase_product_quantity/<int:order_id>/', views.insert_purchase_product_quantity),
    path('find_warehouse_id/', views.find_warehouse_id),
    


]