# Generated by Django 2.2.15 on 2020-12-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='delivery_free',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
