# Generated by Django 2.2.15 on 2020-12-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0003_auto_20201206_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_own',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='is_own',
            field=models.BooleanField(default=True),
        ),
    ]
