# Generated by Django 2.2.15 on 2020-12-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0004_auto_20201207_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Minimum', 'Minimum'), ('Maximum', 'Maximum')], default='Single', max_length=155)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('purchase_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('selling_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('mrp', models.FloatField(blank=True, default=0.0, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
