# Generated by Django 2.2.15 on 2020-12-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0005_specificationprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationprice',
            name='specification_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
