# Generated by Django 2.2.15 on 2020-12-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0007_paymentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='additional_merchant_info',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='amount',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='cancelissuer_datetime',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='cancelissuer_ref_no',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='client_mobile_number',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='issuer_payment_datetime',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='issuer_payment_ref_no',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='order_datetime',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='payment_reference_id',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='status',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='status_code',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
