# Generated by Django 2.2.15 on 2020-12-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0008_auto_20201208_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='merchant_id',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
