# Generated by Django 2.2.15 on 2020-12-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0010_auto_20201208_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
