# Generated by Django 2.2.15 on 2020-12-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0011_productspecification_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mother_status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Processing', max_length=155),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='mother_status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Processing', max_length=155),
        ),
    ]
