# Generated by Django 2.2.15 on 2020-12-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0012_auto_20201210_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='admin_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
