# Generated by Django 2.2.15 on 2020-12-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0013_productspecification_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shared',
            field=models.BooleanField(default=True),
        ),
    ]
