# Generated by Django 2.2.15 on 2020-12-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0014_product_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
