# Generated by Django 2.2.15 on 2020-12-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0015_auto_20201214_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='backend_domain',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
