# Generated by Django 2.2.15 on 2020-12-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0016_companyinfo_backend_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='mother_specification_id',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
