# Generated by Django 2.2.15 on 2020-12-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0017_productspecification_mother_specification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mother_product_id',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
