# Generated by Django 2.2.15 on 2020-12-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0018_product_mother_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='child_product_id',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
