# Generated by Django 2.2.15 on 2020-12-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0020_remove_product_child_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='mother_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
