# Generated by Django 2.2.15 on 2020-12-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0023_auto_20201220_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherSpecificationPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Minimum', 'Minimum'), ('Maximum', 'Maximum')], default='Single', max_length=155)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('purchase_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('selling_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('mrp', models.FloatField(blank=True, default=0.0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('specification_id', models.IntegerField(blank=True, default=-1, null=True)),
                ('is_own', models.BooleanField(default=True)),
                ('mother_specification_id', models.IntegerField(blank=True, default=-1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='specificationprice',
            name='increament_type',
            field=models.CharField(blank=True, choices=[('Percentage', 'Percentage'), ('Amount', 'Amount')], default='Percentage', max_length=155),
        ),
        migrations.AddField(
            model_name='specificationprice',
            name='increament_value',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
