# Generated by Django 2.2.15 on 2020-12-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0024_auto_20201221_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_status', models.CharField(blank=True, choices=[('None', 'None'), ('Newsletter', 'Newsletter')], default='Newsletter', max_length=155)),
                ('email', models.CharField(blank=True, default='', max_length=64)),
                ('is_subscribed', models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
