# Generated by Django 2.2.15 on 2020-12-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0025_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='product_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Published', 'Published'), ('Cancelled', 'Cancelled')], default='Published', max_length=155),
        ),
    ]
