# Generated by Django 2.2.15 on 2020-12-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0026_productspecification_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productspecification',
            old_name='product_status',
            new_name='specification_status',
        ),
    ]
