# Generated by Django 2.2.15 on 2020-12-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0027_auto_20201222_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='terminal_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
