# Generated by Django 2.2.15 on 2020-12-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0028_order_terminal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='on_hold',
            field=models.BooleanField(default=True),
        ),
    ]
