# Generated by Django 2.2.15 on 2020-12-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0029_productspecification_on_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
