# Generated by Django 2.2.15 on 2020-12-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0030_auto_20201224_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashPaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, default=-1, null=True)),
                ('payment_id', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('create_time', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('update_time', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('transaction_status', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('payment_method', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('intent', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('merchant_invoice_number', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('refund_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('payment_reference_id', models.CharField(blank=True, default='', max_length=1024, null=True)),
            ],
        ),
    ]
