# Generated by Django 2.2.15 on 2020-12-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0032_auto_20201230_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_mother',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
