# Generated by Django 2.2.15 on 2021-01-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0033_order_is_mother'),
    ]

    operations = [
        migrations.CreateModel(
            name='manager_inventory_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_rep_id', models.IntegerField(default=-1)),
                ('manager_status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Found', 'Not Found'), ('Damaged', 'Damaged'), ('Pending', 'Pending')], default='Pending', max_length=155, null=True)),
                ('manager_id', models.IntegerField(default=-1)),
                ('product_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Managers_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField(blank=True, default=-1)),
                ('warehouse_id', models.IntegerField(blank=True, default=-1)),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.IntegerField(blank=True, default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventory_report',
            name='manager_attend',
            field=models.BooleanField(default=False),
        ),
    ]
