# Generated by Django 2.2.15 on 2021-01-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0035_order_is_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mother_site_order_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
