# Generated by Django 2.2.15 on 2021-01-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0036_order_mother_site_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferProductSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.IntegerField(blank=True, null=True)),
                ('specification_id', models.IntegerField(blank=True, null=True)),
                ('requested_qty', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('approved_qty', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('approved_user', models.IntegerField(blank=True, default=-1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('request_setter', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('request_getter', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Declined', 'Declined'), ('Partially Approved', 'Partially Approved')], default='Pending', max_length=155)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('requestee_user', models.IntegerField(blank=True, default=-1, null=True)),
            ],
        ),
    ]
