# Generated by Django 2.2.15 on 2021-01-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0037_transferproductspec_transferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Picked', 'Picked'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=155),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Cancelled', 'Cancelled'), ('Not Ordered', 'Not Ordered')], default='Unpaid', max_length=155),
        ),
    ]
