# Generated by Django 2.2.15 on 2021-01-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0038_auto_20210105_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_order_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
